version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm run build
  post_build:
    commands:
      - aws s3 sync out/ s3://healthen-web --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"